### ISSUE TITLE
Arbitrageur can distribute streamed supertokens to pool

### ISSUE THREAD

**Issue by lajarre** [butterdao/daotreasure#8]

**Comment by vaughnmck** [comment]
From what I understand, we're using super tokens (xDAI-xGNT) in this implementation, so we'll be able to stream directly into the pool without an unwrapping service.

So I believe we can close this issue for now. 

@lajarre lmk if you're happy to close this

**Comment by lajarre** [comment]
That's not the way we planned things. For now the Balancer pool is holding the underlying tokens. The Superfluid stream is set up independently (from the treasury towards a contract) and keepers/arbitrageurs need to get involved to unwrap and move the tokens to the pool.

We could indeed think about changing this architecture and rather pooling the supertokens directly…
